export const ORDERS = [
  {
    coors_from: [61.826116, 34.260047],
    buyer: 'ООО ""Максик""',
    cold_conditions: false,
    seller: 'ООО ""Карел Лес""',
    regio_from: "Республика Карелия",
    addres_from: "Республика Карелия, г. Петрозаводск, Шуйское шоссе",
    addres_to: "порт Балтийск, Балтийск, Калининградская область",
    product_type: "пиломатериалы",
    product_name: "Доска строительная 50*100, 1 сорт",
    count: 800,
    weight: 16.5,
    length: 6,
    width: 0.1,
    height: 0.05,
    volume: 0.03,
    weight_sum: 13200,
    volume_sum: 24.0,
    code1: "4407 11 940 1",
    code2: 91118,
    status: "в работе",
    price: "",
  },
  {
    coors_from: [64.63567, 30.708351],
    buyer: 'ООО ""Максик""',
    cold_conditions: false,
    seller: 'ООО ""Карелиан Вуд Кампани""',
    regio_from: "Республика Карелия",
    addres_from: "Республика карелия, г. Костомукша, шосе Горняков, 201",
    addres_to: "порт Балтийск, Балтийск, Калининградская область",
    product_type: "пиломатериалы",
    product_name: "Сосна европейская 50*100, 1 сорт",
    count: 968,
    weight: 12.75,
    length: 5.1,
    width: 0.1,
    height: 0.05,
    volume: 0.03,
    weight_sum: 12342,
    volume_sum: 24.68,
    code1: "4407 11 940 1",
    code2: 91118,
    status: "в работе",
    price: "",
  },
  {
    coors_from: [69.003976, 33.11209],
    buyer: 'ООО ""Спар-Калининград""',
    cold_conditions: true,
    seller: "ООО «АТЛАНТ-Фиш»",
    regio_from: "Мурманская область",
    addres_from: "Мурманская область, Мурманск, Улица Свердлова, д. 35",
    addres_to: "порт Балтийск, Балтийск, Калининградская область",
    product_type: "рыба",
    product_name: "ТРЕСКА С/М Б/Г S 0,5-1 кг, в брикете",
    count: 600,
    weight: 25,
    length: 0.6,
    width: 0.4,
    height: 0.23,
    volume: 0.06,
    weight_sum: 15000,
    volume_sum: 33.12,
    code1: "0303 63 900 0",
    code2: 572080,
    status: "в работе",
    price: "",
  },
  {
    coors_from: [69.003976, 33.11209],
    buyer: 'ООО ""X5 retail""',
    cold_conditions: true,
    seller: "ООО «АТЛАНТ-Фиш»",
    regio_from: "Мурманская область",
    addres_from: "Мурманская область, Мурманск, Улица Свердлова, д. 35",
    addres_to: "порт Балтийск, Балтийск, Калининградская область",
    product_type: "рыба",
    product_name: "ТРЕСКА С/М Б/Г S 0,5-1 кг, в брикете",
    count: 400,
    weight: 25,
    length: 0.6,
    width: 0.4,
    height: 0.23,
    volume: 0.06,
    weight_sum: 10000,
    volume_sum: 22.08,
    code1: "0303 63 900 0",
    code2: 572080,
    status: "в работе",
    price: "",
  },
  {
    coors_from: [56.231178, 43.470932],
    buyer: 'ООО ""НКОР""',
    cold_conditions: false,
    seller: 'ООО ""Хим-Абсолют""',
    regio_from: "Нижегородская область",
    addres_from: "Нижегородская область, г. Дзержинск, ул. Попова, 13",
    addres_to: "порт Балтийск, Балтийск, Калининградская область",
    product_type: "кислоты",
    product_name: "серная кислота, еврокуб, 1000 л.",
    count: 15,
    weight: 1830,
    length: 1.2,
    width: 1,
    height: 1.165,
    volume: 1.4,
    weight_sum: 27450,
    volume_sum: 20.97,
    code1: "2807 00 000 1",
    code2: 481232,
    status: "в работе",
    price: "",
  },
];

// var source = document.getElementById("current-template").innerHTML;
// var template = Handlebars.compile(source);
// var context = { orders: ORDERS };
// document.getElementById("current-out").innerHTML = template(context);
